# ============================================================
# BACKEND DEPLOYMENT
# ------------------------------------------------------------
# Un Deployment le dice a Kubernetes:
#   "Quiero que mantengas SIEMPRE 2 copias de este contenedor
#    corriendo con esta imagen Docker"
#
# Si un contenedor muere, Kubernetes lo reinicia solo.
# ============================================================

apiVersion: apps/v1        # Version de la API de Kubernetes para Deployments
kind: Deployment           # Tipo de objeto: Deployment
metadata:
  name: backend            # Nombre del deployment (identificador en el cluster)

spec:
  replicas: 1              # 1 replica para encajar en el grupo de nodos t3.micro

  # Le dice al Deployment cuales Pods son "suyos"
  # Debe coincidir EXACTAMENTE con los labels del template de abajo
  selector:
    matchLabels:
      app: backend

  # Esta es la "receta" del contenedor que Kubernetes va a crear
  template:
    metadata:
      labels:
        app: backend       # Etiqueta que identifica este Pod

    spec:
      containers:
        - name: backend
          image: ghcr.io/rosariozambrana/modulo3-backend:latest

          ports:
            - containerPort: 8080    # Puerto en el que corre la app

          # Variables de entorno (equivalente al archivo .env)
          env:
            - name: PORT
              value: "8080"

            - name: NODE_ENV
              value: "production"

            - name: CORS_ORIGIN
              value: "*"

            # IMPORTANTE: Reemplaza con la URL real de tu RDS en AWS
            - name: DATABASE_URL
              value: "postgresql://postgres:TU_PASSWORD@TU_HOST_RDS.us-east-1.rds.amazonaws.com:5432/postgres?schema=public"

          # Cuanta CPU y memoria puede usar este contenedor
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"

          # Kubernetes verifica si el contenedor esta LISTO para recibir trafico
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

          # Kubernetes verifica si el contenedor sigue VIVO (lo reinicia si falla)
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
